version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3002:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/postalservices-db
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - db
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3002/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  db:
    image: postgres:15
    container_name: db-portalservices-postgress
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postalservices-db
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: {}

